### ISSUE TITLE
Number

### ISSUE THREAD

**Issue by guoyanb** [valdersoul/GRAM-CNN#7]
I'm very interested in your work and  I'm implementing GRAM-CNN. By the way,  in your paper,  the training set of NCBI dataset is 5145 mentions . However,  it is 5686 mentions in your '/dataset/ncbi/train.eng'. Could you tell me the reason ?

**Comment by valdersoul** [comment]
Oh, I haven't noticed the difference. I just copy the number from the original paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3951655/). However, to produce the training files in its format, I transfer the original data into this one. Maybe due to the tokenization or some other pre-processing, there is a gap. The train.eng is totally from the original text file.

**Comment by guoyanb** [comment]
Ok, thank you very much for your reply. I will do some algorithmic improvements based on your processing data set.

**Comment by guoyanb** [comment]
Hello! In 'Train GRAMCNN example',  when I run the code using 'python train.py ....', I met the problem that is  IndexError: list index out of range (GRAM-CNN/src/utils.py", line 327, in evaluate return float(eval_lines[1].strip().split()[-1]) ). Moreover, I output the 'eval_lines', it is '[]'. Could you help me solve the problem ?  Thanks!
